server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:confident3/microService-config.git
          
info:
   version: 1111
