
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  profiles:
    active: dev
  application:
    name: provider-8001
#  boot:
#    admin:
#      client:
#        url:  http://localhost:8888
server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
#    healthcheck:
#      enabled: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
info:
    version: 2.0